### ISSUE TITLE
linting C crashes

### ISSUE THREAD

**Issue by LuPro** [paulpaul168/glint#34]
```
Exception in thread Thread-37 (lint_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/luis/data/projects/glint/backend/glint_server/threading.py", line 28, in lint_thread
    lint_project(
  File "/home/luis/data/projects/glint/backend/glint_server/linter_collection/lint.py", line 66, in lint_project
    lint = lint_c_project(path, linter)
TypeError: lint_c_project() takes 1 positional argument but 2 were given
```

**Comment by paulpaul168** [comment]
thats super weird?!
```
def lint_c_project(path: str, linter: str):
    if linter == "cpplint":
        return lint_c_project(path)
    else:
        raise LintError(f"C/C++ linter '{linter}' is not known.")


def lint_c_project(project_path: str):
    files = find_c_files(project_path)
    if files == []:
        return normalize_cpplint([])

    process = subprocess.run(
        ["cpplint"] + files,
        text=True,
        capture_output=True,
    )

    cpplint_res = process.stdout.split("\n")
    return normalize_cpplint(cpplint_res, project_path)
```

**Comment by paulpaul168** [comment]
fixed it
